### ISSUE TITLE
Unnecessary reassignment of variable 

### ISSUE THREAD

**Issue by parkhabit** [fac-13/vith-Mixtape#49]
In your DOM.js file you've written the function `displayMusic` with `music` as a parameter but then instantly reassign it to another variable `musisResult` [here](https://github.com/fac-13/vith-Mixtape/blob/master/DOM.js#L50). Instead, you could just write the function with `musicResult` as the parameter.

**Comment by haydnba** [comment]
I would add that you also never properly declared musicResult as a variable in this code, which could be dangerous:

`musicResult = music` should be `var musicResult = music` ??

But obvs pointless if you avoid the unnecessary reassignment...

😒

**Comment by vlbee** [comment]
fixed with refactoring
