### ISSUE TITLE
Nice App!

### ISSUE THREAD

**Issue by haydnba** [fac-13/vith-Mixtape#51]
I don't really know what to say - its lush.. I can't see any obvious issues but that's because I've been spending a lot of time reading through your logic and dom interaction etc. Your tests seem pretty comprehensive and nicely laid out. There are some issues in reading the code on github but these might be formatting issues that would be avoided in the text editor. Seems like you've done a really good job structuring, accessing and rendering your data... without knowing more about this stuff I can't really comment...

What a mostly useless issue!

😔

**Comment by ybird21** [comment]
Thank uuuu 🙏🙏🙏🙏🙏🙏🙏
